// @flow

module.exports = {
    id: 4,
    words: [
        { foreign: ['corner'], native: ['угол, перекрёсток (улиц, дорог)', 'загонять в угол; припереть к стене', 'расставлять что-л. по углам'], sounds: ['/sounds/c/corner.ogg'] },
        { foreign: ['heavy'], native: ['тяжёлый, крупный, массивный, насыщенный', 'интенсивный, толстый(линия), густой(звук)', 'тяжёлый, неуклюжий, медлител., тугодумн.', '(разг.) крепкое пиво '], sounds: ['/sounds/h/heavy.ogg'] },
        { foreign: ['pleasant'], native: ['приятный, радостный'], sounds: ['/sounds/p/pleasant.ogg'] },
        { foreign: ['salad'], native: ['салат, винегрет', 'всякая всячина, смесь'], sounds: ['/sounds/s/salad.ogg'] },
        { foreign: ['season'], native: ['сезон (время года, игровой, отпусков), период', 'придавать интерес, приправлять (блюдо, разговор)', 'быть выдержанным (вино, древесина), закаленным'], sounds: ['/sounds/s/season.ogg'] },
        { foreign: ['lemon'], native: ['лимон'], sounds: ['/sounds/l/lemon.ogg'] },
        { foreign: ['at'], native: ['у, в, за, на (позиц, положение, процесс, состояние)', 'в, после, во время, в течение (время)', ''], sounds: ['/sounds/a/at.ogg'] },
        { foreign: ['pot'], native: ['горшок, котелок, кастрюля', '(нарк.) "травка", марихуана', ' класть в котелок, варить в котелке', 'сажать, помещать в горш, садить на горш'], sounds: ['/sounds/p/pot.ogg'] },
        { foreign: ['lovely'], native: ['красивый, привлекательный', '(разг.) отличный, восхитительный '], sounds: ['/sounds/l/lovely.ogg'] },
        { foreign: ['such'], native: ['такой', 'подобный; похожий'], sounds: ['/sounds/s/such.ogg'] },
        { foreign: ['make (made, made)'], native: ['делать, создавать', 'готовить (какое-л. блюдо или напиток)', 'являться (частью чего-л.)'], sounds: ['/sounds/m/make.ogg'] },
        { foreign: ['speak (spoke, spoken)'], native: ['говорить; произнести', 'высказыв мнение; отзываться (о ком-л. / чём-л.)'], sounds: ['/sounds/s/speak.ogg'] },
        { foreign: ['speak (spoke, spoken)'], native: ['говорить; произнести', 'высказыв мнение; отзываться (о ком-л. / чём-л.)'], sounds: ['/sounds/s/speak.ogg'] },
        { foreign: ['take (took, taken)'], native: ['брать, хватать', 'овладевать, покарять, захватывать', 'привлекать (взгляд), понимать'], sounds: ['/sounds/t/take.ogg'] },
        { foreign: ['paper'], native: [' бумага', 'газета', 'документ, официальная бумага', 'бумажный, номинальный', 'заворачивать в бумагу, оклеивать обоями '], sounds: ['/sounds/p/paper.ogg'] },
        { foreign: ['steak'], native: ['кусок мяса'], sounds: ['/sounds/s/steak.ogg'] },
        { foreign: ['convenient'], native: ['удобный, подходящий'], sounds: ['/sounds/c/convenient.ogg'] },
        { foreign: ['cafe'], native: ['кафе'], sounds: ['/sounds/c/cafe.ogg'] },
        { foreign: ['coat'], native: ['пиджак, китель', 'пальто', 'слой (снега, лака)', 'покрывать слоем чего-л.'], sounds: ['/sounds/c/coat.ogg'] },
        { foreign: ['need'], native: ['необходимость, нужда', 'нехватка, отсутствие (чего-л.)', 'нуждаться (в чём-л.)', 'требоваться'], sounds: ['/sounds/n/need.ogg'] },
        { foreign: ['deserve'], native: ['заслуживать, быть достойным чего-л.'], sounds: ['/sounds/d/deserve.ogg'] },
        { foreign: ['require'], native: ['требовать (чего-л.)'], sounds: ['/sounds/r/require.ogg'] },
        { foreign: ['want'], native: ['желать, хотеть', '(разг.) быть нужным, необходимым; требоваться'], sounds: ['/sounds/w/want.ogg'] },
        { foreign: ['coerce'], native: ['удерживать силой', 'принуждать (к действию или выбору)'], sounds: ['/sounds/c/coerce.ogg'] },
        { foreign: ['drawer'], native: ['(выдвижной) ящик (стола, комода)', 'чертёжник'], sounds: ['/sounds/d/drawer.ogg'] },
        { foreign: ['intent'], native: ['намерение, замысел, цель', 'поглощённый, занятый (работой)'], sounds: ['/sounds/i/intent.ogg'] },
        { foreign: ['drone'], native: ['трутень', 'тунеядец', 'гудение, гул, жужжание'], sounds: ['/sounds/d/drone.ogg'] },
        { foreign: ['firm'], native: ['крепкий', 'непоколебимый', 'крепко', 'уплотнять, улаживать', 'фирма'], sounds: ['/sounds/f/firm.ogg'] },
        { foreign: ['cure'], native: ['лечение, лекарство, излечивать', 'cредство решения какой-л. проблемы ', 'заготавливать, консервировать'], sounds: ['/sounds/c/cure.ogg'] },
        { foreign: ['upright'], native: ['вертикальный', 'колонна'], sounds: ['/sounds/u/upright.ogg'] },
    ],
    title: 'Lesson 4. Table.'
};
