// @flow

module.exports = {
    id: 1,
    words: [
        { foreign: ['hare'], native: ['заяц'], sounds: ['/sounds/h/hare.ogg'] },
        { foreign: ['careless'], native: ['небрежный', 'невнимательный', 'несерьёзный'], sounds: ['/sounds/c/careless.ogg'] },
        { foreign: ['next'], native: ['cледующий', 'ближайший'], sounds: ['/sounds/n/next.ogg'] },
        { foreign: ['bee'], native: ['пчела'], sounds: ['/sounds/b/bee.ogg'] },
        { foreign: ['cover'], native: ['крышка', 'обложка', 'укрытие'], sounds: ['/sounds/c/cover.ogg'] },
        { foreign: ['tea'], native: ['чай'], sounds: ['/sounds/t/tea.ogg'] },
        { foreign: ['declare'], native: ['заявлять'], sounds: ['/sounds/d/declare.ogg'] },
        { foreign: ['affirm'], native: ['подтверждать', 'поддерживать', 'заявлять о поддержке'], sounds: ['/sounds/a/affirm.ogg'] },
        { foreign: ['interrogate'], native: ['выспрашивать', 'допрашивать'], sounds: ['/sounds/i/interrogate.ogg'] },
        { foreign: ['switch'], native: ['выключатель', 'переключение', 'изменение (темы, направления)'], sounds: ['/sounds/s/switch.ogg'] },
        { foreign: ['pet'], native: ['любимое домашнее животное', 'любимец', 'ласкать'], sounds: ['/sounds/p/pet.ogg'] },
        { foreign: ['tent'], native: ['палатка'], sounds: ['/sounds/t/tent.ogg'] },
        { foreign: ['negative'], native: ['отрицательный'], sounds: ['/sounds/n/negative.ogg'] },
        { foreign: ['exclaim'], native: ['восклицать'], sounds: ['/sounds/e/exclaim.ogg'] },
        { foreign: ['imperative'], native: ['повеление', 'обязательный'], sounds: ['/sounds/i/imperative.ogg'] },
        { foreign: ['meet (met,met)'], native: ['встречать'], sounds: ['/sounds/m/meet.ogg'] },
        { foreign: ['mend'], native: ['починка'], sounds: ['/sounds/m/mend.ogg'] },
        { foreign: ['meat'], native: ['мясо'], sounds: ['/sounds/m/meat.ogg'] },
        { foreign: ['composite'], native: ['смесь'], sounds: [] },
        { foreign: ['gutter'], native: ['канава'], sounds: ['/sounds/g/gutter.ogg'] },
        { foreign: ['win (won, won)'], native: ['победить'], sounds: ['/sounds/w/win.ogg'] },
        { foreign: ['point'], native: ['точка, пятнышко', ' вопрос, дело', 'отличительная черта, особенность ', 'тонкий конец, кончик', 'указывать', 'отмечать, подчёркивать '], sounds: ['/sounds/p/point.ogg'] },
        { foreign: ['lobby'], native: ['вестибюль'], sounds: ['/sounds/l/lobby.ogg'] },
        { foreign: ['lend(lent, lent)'], native: ['одалживать'], sounds: ['/sounds/l/lend.ogg'] },
        { foreign: ['ear'], native: ['ухо'], sounds: ['/sounds/e/ear.ogg'] },
        { foreign: ['set (set, set)'], native: ['ставить', 'приводить в (определённое) состояние'], sounds: ['/sounds/s/set.ogg'] },
        { foreign: ['seat'], native: ['сиденье'], sounds: ['/sounds/s/seat.ogg'] },
        { foreign: ['facility'], native: ['возможность', 'услуги', 'удобства', 'доступность'], sounds: ['/sounds/f/facility.ogg'] },
        { foreign: ['embrace'], native: ['обниматься', 'выбирать', 'заключать в себе, охватывать '], sounds: ['/sounds/e/embrace.ogg'] },
        { foreign: ['impact'], native: ['удар, толчок', 'сильное воздействие'], sounds: ['/sounds/i/impact01.mp3'] },
        { foreign: ['light'], native: ['свет', 'освещение', 'лампа'], sounds: ['/sounds/l/light.ogg'] },
        { foreign: ['handle'], native: ['рукоять', 'повод, предлог', 'управлять (чем-л.), справляться (с чем-л.), обрабатывать (что-л.)'], sounds: ['/sounds/h/handle.ogg'] },
        { foreign: ['ledge'], native: ['полочка', 'выступ'], sounds: ['/sounds/l/ledge.ogg'] },
    ],
    title: 'Lesson 1. Switch board.'
};
