// @flow

module.exports = {
    id: 3,
    words: [
        { foreign: ['lever'], native: ['рычаг'], sounds: ['/sounds/l/lever.ogg'] },
        { foreign: ['button'], native: ['пуговица', 'кнопка'], sounds: ['/sounds/b/button.ogg'] },
        { foreign: ['key'], native: ['ключ'], sounds: ['/sounds/k/key.ogg'] },
        { foreign: ['helix'], native: ['спираль', 'завиток ушной раковины'], sounds: ['/sounds/h/helix.mp3'] },
        { foreign: ['tube'], native: ['труба, трубка', 'тюбик', 'пробирка'], sounds: ['/sounds/t/tube.ogg'] },
        { foreign: ['soap'], native: ['мыло', 'мылить, тереть мылом'], sounds: ['/sounds/s/soap.ogg'] },
        { foreign: ['model'], native: ['модель, макет', 'образец, эталон', 'натурщик', 'моделировать'], sounds: ['/sounds/m/model.ogg'] },
        { foreign: ['bottle'], native: ['бутылка, флакон, склянка, фляга', 'спиртное, выпивка', 'хранить в бутылках'], sounds: ['/sounds/b/bottle.ogg'] },
        { foreign: ['on'], native: ['на, по (в простр.)', 'в (в определен день недели, дату, момент дня)', 'после (последоват)', 'во время (одновременю действ.)'], sounds: ['/sounds/o/on.ogg'] },
        { foreign: ['hot'], native: ['горячий, жаркий', 'острый, пикантный', 'возбуждённый'], sounds: ['/sounds/h/hot.ogg'] },
        { foreign: ['hold (held, held)'], native: ['держать', 'удерживать', 'придерживаться (мнения)', 'ручка, захват, ушко, опора', 'нора, трюм, убежище'], sounds: ['/sounds/h/hold.ogg'] },
        { foreign: ['shelf'], native: ['полка', 'риф, отмель, шельф'], sounds: ['/sounds/s/shelf.ogg'] },
        { foreign: ['ship'], native: ['корабль'], sounds: ['/sounds/s/ship.ogg'] },
        { foreign: ['idle'], native: ['тщетный', 'неиспользуемый', '(тех.) бездействующий, холостой', 'бездельничать'], sounds: ['/sounds/i/idle.ogg'] },
        { foreign: ['tape'], native: ['тесьма; лента, ленточка финиша', 'рулетка, змерять рулеткой'], sounds: ['/sounds/t/tape.ogg'] },
        { foreign: ['plane'], native: ['плоская поверхность', 'самолёт, несущ поверхн крыла, планировать', 'плоский', 'ровнять, выравнивать, сглаживать'], sounds: ['/sounds/p/plane.ogg'] },
        { foreign: ['say (said, said)'], native: ['говорить, произносить'], sounds: ['/sounds/s/say.ogg'] },
        { foreign: ['pay (paid , paid)'], native: ['платить', 'отплатить, отомстить', ' оказывать, обращать (внимание)', 'платный'], sounds: ['/sounds/p/pay.ogg'] },
        { foreign: ['stay'], native: ['пребывание', 'оставаться'], sounds: ['/sounds/s/stay.ogg'] },
        { foreign: ['leave'], native: ['позволение, разрешение (to ask leave (to do smth.))', 'увольнительная, отпуск', 'расставание, прощание'], sounds: ['/sounds/l/leave.ogg'] },
        { foreign: ['lazy'], native: ['ленивый'], sounds: ['/sounds/l/lazy.ogg'] },
        { foreign: ['flat'], native: ['плоскость, полотно(пилы)', 'плоскодонка (судно с плоским дном)', 'плоский (прям и перен.), не контрастн', 'квартира'], sounds: ['/sounds/f/flat.ogg'] },
        { foreign: ['lamp'], native: ['лампа, светильник', ' освещать; светить, сиять (прям. и перен.)'], sounds: ['/sounds/l/lamp.ogg'] },
        { foreign: ['pad'], native: ['прокладка; набивка', 'подушка; тампон (мед.)', 'блокнот', 'набивать (волосом, ватой плечики)', 'раздувать (счёт, штаты)'], sounds: ['/sounds/p/pad.ogg'] },
        { foreign: ['ham'], native: ['бедро, ляжка', 'ветчина, окорок'], sounds: ['/sounds/h/ham.ogg'] },
        { foreign: ['pie'], native: ['пирог; пирожок'], sounds: ['/sounds/p/pie.ogg'] },
        { foreign: ['stamp'], native: ['штамп, печать', 'клеймо, пломба', '(почтовая) марка', 'отпечаток, след', 'штамповать, клеймить, отпечатывать, оттискивать, наклеивать марку'], sounds: ['/sounds/s/stamp.ogg'] },
        { foreign: ['map'], native: ['карта', 'изображать в виде карты'], sounds: ['/sounds/m/map.ogg'] },
        { foreign: ['plan'], native: ['план; проект', 'схема, чертёж', 'запланировать'], sounds: ['/sounds/p/plan.ogg'] },
        { foreign: ['splendid'], native: ['роскошный', 'разг. отменный'], sounds: ['/sounds/s/splendid.ogg'] },
        { foreign: ['niece'], native: ['племянница'], sounds: ['/sounds/n/niece.ogg'] },
    ],
    title: 'Lesson 3. Intercom.'
};
