// @flow
export const SETTINGS_REQUEST: Type = 'SETTINGS/FETCH_REQUEST';
export const SETTINGS_SUCCESS: Type = 'SETTINGS/FETCH_SUCCESS';
export const SETTINGS_FAILURE: Type = 'SETTINGS/FETCH_FAILURE';
export const SETTINGS_CANCEL: Type = 'SETTINGS/FETCH_CANCEL';

export const RESET: Type = 'SETTINGS/RESET';
