// @flow
export const SETTINGS_FETCH_REQUEST: Type = 'SETTINGS/FETCH_REQUEST';
export const SETTINGS_FETCH_SUCCESS: Type = 'SETTINGS/FETCH_SUCCESS';
export const SETTINGS_FETCH_FAILURE: Type = 'SETTINGS/FETCH_FAILURE';
export const SETTINGS_FETCH_CANCEL: Type = 'SETTINGS/FETCH_CANCEL';

export const SETTINGS_RESET: Type = 'SETTINGS/RESET';

export const SETTINGS_STORE_REQUEST: Type = 'SETTINGS/STORE_REQUEST';
export const SETTINGS_STORE_SUCCESS: Type = 'SETTINGS/STORE_SUCCESS';
export const SETTINGS_STORE_FAILURE: Type = 'SETTINGS/STORE_FAILURE';
export const SETTINGS_STORE_CANCEL: Type = 'SETTINGS/STORE_CANCEL';
