// @flow
export const SETTINGS_FETCH_REQUEST: Type = 'SETTINGS/FETCH_REQUEST';
export const SETTINGS_FETCH_SUCCESS: Type = 'SETTINGS/FETCH_SUCCESS';
export const SETTINGS_FETCH_FAILURE: Type = 'SETTINGS/FETCH_FAILURE';
export const SETTINGS_FETCH_CANCEL: Type = 'SETTINGS/FETCH_CANCEL';

export const SETTINGS_RESET: Type = 'SETTINGS/RESET';

export const SETTINGS_SAVE_REQUEST: Type = 'SETTINGS/SAVE_REQUEST';
export const SETTINGS_SAVE_SUCCESS: Type = 'SETTINGS/SAVE_SUCCESS';
export const SETTINGS_SAVE_FAILURE: Type = 'SETTINGS/SAVE_FAILURE';
export const SETTINGS_SAVE_CANCEL: Type = 'SETTINGS/SAVE_CANCEL';
