// @flow
export const FETCH_REQUEST: Type = 'HOME_COMPONENT/FETCH_REQUEST';
export const FETCH_SUCCESS: Type = 'HOME_COMPONENT/FETCH_SUCCESS';
export const FETCH_FAILURE: Type = 'HOME_COMPONENT/FETCH_FAILURE';
export const FETCH_CANCEL: Type = 'HOME_COMPONENT/FETCH_CANCEL';

export const RESET: Type = 'HOME_COMPONENT/RESET';
